/**
 * API Client Configuration
 *
 * This file configures the generated API client and provides utilities
 * for integrating with SWR (Stale-While-Revalidate).
 *
 * The generated client is located in ./generated/ and includes:
 * - TypeScript interfaces (models/) - All types from backend Pydantic schemas
 * - Service classes (services/) - API endpoint implementations
 * - Core HTTP client (core/) - Fetch-based HTTP implementation
 *
 * Generated by: openapi-typescript-codegen
 * Source: http://localhost:8000/openapi.json (FastAPI OpenAPI spec)
 */

import { ApiClient } from "./generated/ApiClient";
import { OpenAPI } from "./generated/core/OpenAPI";

// Configure the OpenAPI client
OpenAPI.BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
OpenAPI.VERSION = "2.0.0";
OpenAPI.WITH_CREDENTIALS = false;

// Create API client instance with services
export const api = new ApiClient(OpenAPI);

// Export all types for use in components
export * from "./generated/index";

/**
 * SWR Fetcher function for use with generated API services
 *
 * Usage:
 * ```typescript
 * const { data, error, isLoading } = useSWR(
 *   ['/api/company/VCB/overview'],
 *   () => fetcher(() => api.company.getCompanyOverviewEndpointApiCompanyTickerOverviewGet({ ticker: 'VCB' }))
 * );
 * ```
 */
export const fetcher = async <T>(apiCall: () => Promise<T>): Promise<T> => {
  try {
    return await apiCall();
  } catch (error) {
    throw new Error(
      error instanceof Error ? error.message : "Unknown API error"
    );
  }
};

/**
 * SWR Configuration helper for API calls
 *
 * Makes it easier to use SWR with the generated API client:
 *
 * Example:
 * ```typescript
 * const { data, error } = useSWR(
 *   ['company-overview', 'VCB'],
 *   () => createApiCall(api.company.getCompanyOverviewEndpointApiCompanyTickerOverviewGet, { ticker: 'VCB' })
 * );
 * ```
 */
export const createApiCall =
  <T, Args extends Record<string, unknown>>(
    serviceMethod: (args: Args) => Promise<T>,
    args: Args
  ) =>
  (): Promise<T> => {
    return serviceMethod(args);
  };
